gather the futures into a map "manually", i.e. using a forEach instead of a collect
It seams that the collector does not support the update of a value: if a key has two or more values, an IllegalStateException is thrown

   error while pulling.
   java.lang.IllegalStateException: Duplicate key http://cyberlearn.hes-so.ch/pluginfile.php/35122/mod_label/intro/Core_CSharp_and_.NET_Quick_Reference.pdf
        at java.util.stream.Collectors.lambda$throwingMerger$110(Collectors.java:133)
        at java.util.stream.Collectors$$Lambda$40/7967307.apply(Unknown Source)
        ...

To avoid that, replace:
        .collect( Collectors.toMap( NameValuePair::getName, NameValuePair::getValue ) );
by:
        .forEach( (pair) -> { result.put( pair.getName(), pair.getValue() ); } );

less fancy, but works...